services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mariadb_data:

networks:
  app_network:
    driver: bridge